@startuml
package com.greybox.projectmesh.extension {
  class UriNameAndSize {
    +name: String?
    +size: Long
  }

  class ContentResolver <<Android>> {
    +query(uri: Uri, projection: Array<String>?, selection: String?, selectionArgs: Array<String>?, sortOrder: String?): Cursor?
  }

  class Cursor <<Android>> {
    +moveToFirst(): Boolean
    +getColumnIndex(columnName: String): Int
    +isNull(columnIndex: Int): Boolean
    +getString(columnIndex: Int): String?
    +close()
  }

  class ContentResolverExtension <<(E,#FF7700)>> {
    +getUriNameAndSize(uri: Uri): UriNameAndSize
  }
}

ContentResolverExtension ..> ContentResolver : extension
ContentResolverExtension ..> Cursor : uses
ContentResolverExtension --> UriNameAndSize : returns
@enduml
