@startuml MessageRepository
skinparam classAttributeIconSize 0

class MessageRepository {
  - messageDao : MessageDao
  + getChatMessages(chatId: String) : Flow<List<Message>>
  + addMessage(message: Message)
  + getAllMessages() : Flow<List<Message>>
  + clearMessages()
}

interface MessageDao {
  + getChatMessagesFlow(chat: String) : Flow<List<Message>>
  + getAllFlow() : Flow<List<Message>>
  + addMessage(m: Message)
  + clearTable()
}

class Message

MessageRepository --> MessageDao
MessageRepository ..> Message
@enduml
