@startuml InputStreamCounter

package "java.io" {
    class InputStream
    class FilterInputStream {
        - in: InputStream
        + read(): int
        + read(b: byte[], off: int, len: int): int
        + close(): void
    }
    FilterInputStream --> InputStream
}

package "com.greybox.projectmesh.server" {
    class InputStreamCounter extends FilterInputStream {
        + bytesRead: Int
        + closed: Boolean

        + read(): Int
        + read(b: ByteArray, off: Int, len: Int): Int
        + close(): Void
    }
}

InputStreamCounter --> InputStream : wraps

@enduml
