@startuml
package com.greybox.projectmesh.viewModel {
  class SendScreenModel {
    +outgoingTransfers: List<AppServer.OutgoingTransferInfo>
  }

  class SendScreenViewModel {
    -_uiState: MutableStateFlow<SendScreenModel>
    +uiState: Flow<SendScreenModel>
    -appServer: AppServer
    -onSwitchToSelectDestNode: (List<Uri>) -> Unit
    +onFileChosen(uris: List<Uri>)
    +onDelete(transfer: AppServer.OutgoingTransferInfo)
  }
}

package com.greybox.projectmesh.server {
  class AppServer {
    +outgoingTransfers: Flow<List<OutgoingTransferInfo>>
    +removeOutgoingTransfer(id: Int)
  }

  class OutgoingTransferInfo {
    +id: Int
    +name: String
    +uri: Uri
    +toHost: InetAddress
    +size: Int
  }
}

SendScreenViewModel --> AppServer : uses
SendScreenViewModel --> SendScreenModel : updates
SendScreenViewModel --> Uri : passes
AppServer --> OutgoingTransferInfo : emits/accepts
@enduml
