@startuml
package com.greybox.projectmesh.user {
  interface UserDao {
    +getUserByUuid(uuid: String): UserEntity?
    +insertUser(user: UserEntity)
    +updateUser(user: UserEntity)
    +hasWithID(uuid: String): Boolean
    +getUserByIp(ip: String): UserEntity?
    +getAllConnectedUsers(): List<UserEntity>
    +getAllUsers(): List<UserEntity>
  }

  class UserEntity {
    +uuid: String
    +name: String
    +address: String?
    +lastSeen: Long?
  }

  class UserRepository {
    -userDao: UserDao
    +insertOrUpdateUser(uuid: String, name: String, address: String?)
    +getUserByIp(ip: String): UserEntity?
    +getUser(uuid: String): UserEntity?
    +getAllConnectedUsers(): List<UserEntity>
    +getAllUsers(): List<UserEntity>
    +hasUser(uuid: String): Boolean
  }

  UserRepository --> UserDao : uses
  UserDao --> UserEntity : returns/accepts
}
@enduml
